Is this section I am gonna show 
some basics arithmetic operation like power , Modulus ,
addition , multiplication , Division


In [ ]:
import numpy as ex

a = ex.array([1,2,3,4])
b = ex.array([5,6,7,8])

add_ex = ex.add(a, b)# for addition
sub_ex=ex.subtract(a,b)# for subtract
mul_ex=ex.multiply(a, b)# for multiply
div_ex=ex.divide(a,b)# for division
pow_ex=ex.power(a,b)# for power
print(pow_ex)
print(div_ex)
print(mul_ex)
print(sub_ex)
print(add_ex)

[0.2        0.33333333 0.42857143 0.5       ]
[ 5 12 21 32]
[-4 -4 -4 -4]
[ 6  8 10 12]
